
server:
  port: 8020

spring:
  application:
    name: mq-bank2

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mq_bank2?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root


rocketmq:
  name-server: 192.168.3.100:9876
  consumer:
    group: consumer_txmsg
    topic: topic_txmsg