server:
  port: 8010

spring:
  application:
    name: mq-bank1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mq_bank1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

rocketmq:
  name-server: 192.168.3.100:9876
  producer:
    group: producer_bank1
